In [81]:
import numpy as np
import pandas as pd

In [61]:
array = np.array([[1000, 2, 4], [1500, 3, 1]])

In [62]:
array

array([[1000,    2,    4],
       [1500,    3,    1]])

In [39]:
np.mean(array[:,0])

1250.0

### Activity for Data Scaling: Max_Min Scaler
A 2D array is given, write a function that for each column:
1. (min) Obtain the minimum value
2. (range)Obtain the range
3. (value-min) / range 

In [40]:
array.shape

(2, 3)

In [41]:
def max_min_scaler(a):
    a = np.copy(a)
    for col_num in range(a.shape[1]): 
        min_val = np.min(a[:, col_num])
        range_val = np.max(a[:, col_num]) - min_val
        a[:, col_num] = (a[:, col_num] - min_val) / range_val
    
    return a

In [42]:
max_min_scaler(array)

array([[0, 0, 1],
       [1, 1, 0]])

In [44]:
from sklearn import preprocessing

In [47]:
min_max_scaler = preprocessing.MinMaxScaler()
X_minmax = min_max_scaler.fit_transform(array)

In [48]:
X_minmax

array([[0., 0., 1.],
       [1., 1., 0.]])

In [78]:
def standard_scaler(a):
    def scale_col(col):
        return (col - np.mean(col)) / np.std(col)
        
    a = np.copy(a)
    for col_num in range(a.shape[1]):
        a[:, col_num] = scale_col(a[:, col_num])
    
    return a

In [79]:
standard_scaler(array)

array([[-1, -1,  1],
       [ 1,  1, -1]])

In [71]:
array

array([[1000,    2,    4],
       [1500,    3,    1]])

In [82]:
df = pd.read_csv('data/churn_modelling.csv')

In [86]:
df['Gender'].unique()

array(['Female', 'Male'], dtype=object)

In [93]:
data = df.iloc[:, 3:13].values

In [94]:
target = df.iloc[:, 13].values

In [95]:
data

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [96]:
data[0:10, :]

array([[619, 'France', 'Female', 42, 2, 0.0, 1, 1, 1, 101348.88],
       [608, 'Spain', 'Female', 41, 1, 83807.86, 1, 0, 1, 112542.58],
       [502, 'France', 'Female', 42, 8, 159660.8, 3, 1, 0, 113931.57],
       [699, 'France', 'Female', 39, 1, 0.0, 2, 0, 0, 93826.63],
       [850, 'Spain', 'Female', 43, 2, 125510.82, 1, 1, 1, 79084.1],
       [645, 'Spain', 'Male', 44, 8, 113755.78, 2, 1, 0, 149756.71],
       [822, 'France', 'Male', 50, 7, 0.0, 2, 1, 1, 10062.8],
       [376, 'Germany', 'Female', 29, 4, 115046.74, 4, 1, 0, 119346.88],
       [501, 'France', 'Male', 44, 4, 142051.07, 2, 0, 1, 74940.5],
       [684, 'France', 'Male', 27, 2, 134603.88, 1, 1, 1, 71725.73]],
      dtype=object)

In [97]:
label_encoder_data_1 = preprocessing.LabelEncoder()
label_encoder_data_2 = preprocessing.LabelEncoder()

In [98]:
data[:, 1] = label_encoder_data_1.fit_transform(data[:, 1])

In [99]:
data[:, 2] = label_encoder_data_1.fit_transform(data[:, 2])